# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bullSpreadViewSmall.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!
# todo use return key to activate "Qualify Contracts"

from PyQt5 import QtCore, QtGui, QtWidgets
from ib_insync import *

# need to give QT the async from ib_insync
util.useQt()

# Option management classes for PyOptions - mrk
import buildVerticalSpreadViews, buildIronCondorViews

from localUtilities import errorHandler, configIB, dateUtils, logger

class Ui_MainPyOptionsWindow(object):
    """
    an_option_spread is the created option spread
    """
    def __init__(self):
        self.ib = IB()
        self.ib.setCallback('error', errorHandler.onError)

    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< def setup Ui -- goes here:<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    def setupUi(self, MainPyOptionsWindow):
        MainPyOptionsWindow.setObjectName("MainPyOptionsWindow")
        MainPyOptionsWindow.resize(1221, 838)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icons/ib.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainPyOptionsWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainPyOptionsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-10, 0, 1181, 761))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_optionSpreads = QtWidgets.QWidget()
        self.page_optionSpreads.setObjectName("page_optionSpreads")
        self.tabWidget_Contracts = QtWidgets.QTabWidget(self.page_optionSpreads)
        self.tabWidget_Contracts.setGeometry(QtCore.QRect(20, 40, 1161, 711))
        self.tabWidget_Contracts.setObjectName("tabWidget_Contracts")
        self.qualifyContracts_tab = QtWidgets.QWidget()
        self.qualifyContracts_tab.setObjectName("qualifyContracts_tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.qualifyContracts_tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 291, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.qualifyContracts = QtWidgets.QPushButton(self.groupBox_2)
        self.qualifyContracts.setGeometry(QtCore.QRect(160, 220, 111, 23))
        self.qualifyContracts.setObjectName("qualifyContracts")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setGeometry(QtCore.QRect(20, 30, 185, 17))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radioButton_Index = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_Index.setChecked(True)
        self.radioButton_Index.setObjectName("radioButton_Index")
        self.radioButton_Stock = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_Stock.setObjectName("radioButton_Stock")
        self.radioButton_Option = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_Option.setObjectName("radioButton_Option")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(17, 81, 250, 50))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.labelExchange = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.labelExchange.setFont(font)
        self.labelExchange.setWhatsThis("")
        self.labelExchange.setObjectName("labelExchange")
        self.gridLayout.addWidget(self.labelExchange, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.underlyingText = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.underlyingText.setObjectName("underlyingText")
        self.gridLayout.addWidget(self.underlyingText, 1, 0, 1, 1)
        self.comboBoxExchange = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBoxExchange.setToolTip("")
        self.comboBoxExchange.setObjectName("comboBoxExchange")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.gridLayout.addWidget(self.comboBoxExchange, 1, 1, 1, 1)
        self.comboBox_Expiry = QtWidgets.QComboBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.comboBox_Expiry.setFont(font)
        self.comboBox_Expiry.setObjectName("comboBox_Expiry")
        self.gridLayout.addWidget(self.comboBox_Expiry, 1, 2, 1, 1)
        self.groupBox_StrikePrice = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_StrikePrice.setGeometry(QtCore.QRect(17, 140, 251, 51))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.groupBox_StrikePrice.setFont(font)
        self.groupBox_StrikePrice.setObjectName("groupBox_StrikePrice")
        self.label_4 = QtWidgets.QLabel(self.groupBox_StrikePrice)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 41, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_StrikePrice)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 51, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_StrikePriceRange = QtWidgets.QComboBox(self.groupBox_StrikePrice)
        self.comboBox_StrikePriceRange.setGeometry(QtCore.QRect(50, 30, 51, 16))
        self.comboBox_StrikePriceRange.setObjectName("comboBox_StrikePriceRange")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceMultiple = QtWidgets.QComboBox(self.groupBox_StrikePrice)
        self.comboBox_StrikePriceMultiple.setGeometry(QtCore.QRect(170, 30, 51, 16))
        self.comboBox_StrikePriceMultiple.setObjectName("comboBox_StrikePriceMultiple")
        self.comboBox_StrikePriceMultiple.addItem("")
        self.comboBox_StrikePriceMultiple.addItem("")
        self.comboBox_StrikePriceMultiple.addItem("")
        self.comboBox_StrikePriceMultiple.addItem("")
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_7.setGeometry(QtCore.QRect(19, 50, 121, 25))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_CallPut = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.gridLayout_CallPut.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_CallPut.setObjectName("gridLayout_CallPut")
        self.radioButton_Call = QtWidgets.QRadioButton(self.layoutWidget_7)
        self.radioButton_Call.setChecked(True)
        self.radioButton_Call.setObjectName("radioButton_Call")
        self.gridLayout_CallPut.addWidget(self.radioButton_Call, 0, 0, 1, 1)
        self.radioButton_Put = QtWidgets.QRadioButton(self.layoutWidget_7)
        self.radioButton_Put.setObjectName("radioButton_Put")
        self.gridLayout_CallPut.addWidget(self.radioButton_Put, 0, 1, 1, 1)
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_8.setGeometry(QtCore.QRect(17, 220, 120, 25))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.gridLayout_CallPut_2 = QtWidgets.QGridLayout(self.layoutWidget_8)
        self.gridLayout_CallPut_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_CallPut_2.setObjectName("gridLayout_CallPut_2")
        self.radioButton_MktDataType_Frozen = QtWidgets.QRadioButton(self.layoutWidget_8)
        self.radioButton_MktDataType_Frozen.setChecked(True)
        self.radioButton_MktDataType_Frozen.setObjectName("radioButton_MktDataType_Frozen")
        self.gridLayout_CallPut_2.addWidget(self.radioButton_MktDataType_Frozen, 0, 0, 1, 1)
        self.radioButton_MktDataType_Live = QtWidgets.QRadioButton(self.layoutWidget_8)
        self.radioButton_MktDataType_Live.setObjectName("radioButton_MktDataType_Live")
        self.gridLayout_CallPut_2.addWidget(self.radioButton_MktDataType_Live, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(20, 40, 191, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 111, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tableWidget = QtWidgets.QTableWidget(self.qualifyContracts_tab)
        self.tableWidget.setGeometry(QtCore.QRect(320, 30, 461, 221))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(19)
        self.tableWidget.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_OptionGreeks = QtWidgets.QTableWidget(self.qualifyContracts_tab)
        self.tableWidget_OptionGreeks.setGeometry(QtCore.QRect(30, 310, 841, 341))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        self.tableWidget_OptionGreeks.setFont(font)
        self.tableWidget_OptionGreeks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_OptionGreeks.setAlternatingRowColors(True)
        self.tableWidget_OptionGreeks.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_OptionGreeks.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_OptionGreeks.setRowCount(6)
        self.tableWidget_OptionGreeks.setColumnCount(9)
        self.tableWidget_OptionGreeks.setObjectName("tableWidget_OptionGreeks")
        self.tableWidget_OptionGreeks.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget_OptionGreeks.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_OptionGreeks.verticalHeader().setVisible(False)
        self.tableWidget_OptionGreeks.verticalHeader().setDefaultSectionSize(19)
        self.label_2 = QtWidgets.QLabel(self.qualifyContracts_tab)
        self.label_2.setGeometry(QtCore.QRect(30, 290, 101, 17))
        font = QtGui.QFont()
        font.setFamily("MathJax_Main")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.qualifyContracts_tab)
        self.label_7.setGeometry(QtCore.QRect(320, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily("MathJax_Main")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tabWidget_Contracts.addTab(self.qualifyContracts_tab, "")
        self.bullSpread_tab = QtWidgets.QWidget()
        self.bullSpread_tab.setObjectName("bullSpread_tab")
        self.tableWidget_BullCallSpread = QtWidgets.QTableWidget(self.bullSpread_tab)
        self.tableWidget_BullCallSpread.setGeometry(QtCore.QRect(20, 70, 451, 571))
        self.tableWidget_BullCallSpread.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_BullCallSpread.setAlternatingRowColors(True)
        self.tableWidget_BullCallSpread.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_BullCallSpread.setRowCount(5)
        self.tableWidget_BullCallSpread.setColumnCount(4)
        self.tableWidget_BullCallSpread.setObjectName("tableWidget_BullCallSpread")
        self.tableWidget_BullCallSpread.horizontalHeader().setDefaultSectionSize(105)
        self.tableWidget_BullCallSpread.horizontalHeader().setMinimumSectionSize(11)
        self.tableWidget_BullCallSpread.verticalHeader().setDefaultSectionSize(25)
        self.layoutWidget_9 = QtWidgets.QWidget(self.bullSpread_tab)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 10, 260, 28))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.spinBox_numberOfContracts = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_numberOfContracts.setMinimum(1)
        self.spinBox_numberOfContracts.setMaximum(15)
        self.spinBox_numberOfContracts.setObjectName("spinBox_numberOfContracts")
        self.horizontalLayout.addWidget(self.spinBox_numberOfContracts)
        self.pushButton_updateNumberOfContracts = QtWidgets.QPushButton(self.layoutWidget_9)
        self.pushButton_updateNumberOfContracts.setObjectName("pushButton_updateNumberOfContracts")
        self.horizontalLayout.addWidget(self.pushButton_updateNumberOfContracts)
        self.label_9 = QtWidgets.QLabel(self.bullSpread_tab)
        self.label_9.setGeometry(QtCore.QRect(480, 50, 191, 20))
        self.label_9.setStyleSheet("font: 75 italic 11pt \"aakar\";\n"
"color: rgb(32, 74, 135);")
        self.label_9.setObjectName("label_9")
        self.tableWidget_BullPutSpread = QtWidgets.QTableWidget(self.bullSpread_tab)
        self.tableWidget_BullPutSpread.setGeometry(QtCore.QRect(480, 70, 451, 571))
        self.tableWidget_BullPutSpread.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_BullPutSpread.setAlternatingRowColors(True)
        self.tableWidget_BullPutSpread.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_BullPutSpread.setRowCount(5)
        self.tableWidget_BullPutSpread.setColumnCount(4)
        self.tableWidget_BullPutSpread.setObjectName("tableWidget_BullPutSpread")
        self.tableWidget_BullPutSpread.horizontalHeader().setDefaultSectionSize(105)
        self.tableWidget_BullPutSpread.horizontalHeader().setMinimumSectionSize(11)
        self.tableWidget_BullPutSpread.verticalHeader().setDefaultSectionSize(25)
        self.label_10 = QtWidgets.QLabel(self.bullSpread_tab)
        self.label_10.setGeometry(QtCore.QRect(20, 50, 191, 20))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font: 75 italic 11pt \"aakar\";\n"
"color: rgb(32, 74, 135);")
        self.label_10.setObjectName("label_10")
        self.line = QtWidgets.QFrame(self.bullSpread_tab)
        self.line.setGeometry(QtCore.QRect(20, 35, 271, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.tabWidget_Contracts.addTab(self.bullSpread_tab, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 751, 561))
        self.tableWidget_2.setRowCount(10)
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tabWidget_Contracts.addTab(self.tab3, "")
        self.layoutWidget = QtWidgets.QWidget(self.page_optionSpreads)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 341, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setStyleSheet("font: 75 italic 12pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.lineEdit_underlying = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_underlying.setReadOnly(True)
        self.lineEdit_underlying.setObjectName("lineEdit_underlying")
        self.horizontalLayout_2.addWidget(self.lineEdit_underlying)
        self.label_12 = QtWidgets.QLabel(self.page_optionSpreads)
        self.label_12.setGeometry(QtCore.QRect(910, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font: 75 italic 20pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_optionSpreads)
        self.label_13.setGeometry(QtCore.QRect(830, 10, 71, 41))
        self.label_13.setStyleSheet("image: url(:/resources/icons/download.ico);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_optionSpreads)
        self.page_ironCondor = QtWidgets.QWidget()
        self.page_ironCondor.setObjectName("page_ironCondor")
        self.label_15 = QtWidgets.QLabel(self.page_ironCondor)
        self.label_15.setGeometry(QtCore.QRect(830, 10, 71, 41))
        self.label_15.setStyleSheet("image: url(:/resources/icons/ironC.ico);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.page_ironCondor)
        self.label_14.setGeometry(QtCore.QRect(910, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("font: 75 italic 20pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_14.setObjectName("label_14")
        self.groupBox_IC = QtWidgets.QGroupBox(self.page_ironCondor)
        self.groupBox_IC.setGeometry(QtCore.QRect(20, 10, 291, 261))
        self.groupBox_IC.setObjectName("groupBox_IC")
        self.qualifyIronCondor = QtWidgets.QPushButton(self.groupBox_IC)
        self.qualifyIronCondor.setGeometry(QtCore.QRect(160, 220, 121, 23))
        self.qualifyIronCondor.setObjectName("qualifyIronCondor")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_IC)
        self.splitter_2.setGeometry(QtCore.QRect(20, 30, 185, 17))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.radioButton_Index_IC = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_Index_IC.setChecked(True)
        self.radioButton_Index_IC.setObjectName("radioButton_Index_IC")
        self.radioButton_Stock_IC = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_Stock_IC.setObjectName("radioButton_Stock_IC")
        self.radioButton_Option_IC = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_Option_IC.setObjectName("radioButton_Option_IC")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_IC)
        self.layoutWidget_3.setGeometry(QtCore.QRect(17, 81, 250, 50))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_IC = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_IC.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_IC.setObjectName("gridLayout_IC")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_IC.addWidget(self.label_16, 0, 0, 1, 1)
        self.labelExchange_2 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.labelExchange_2.setFont(font)
        self.labelExchange_2.setWhatsThis("")
        self.labelExchange_2.setObjectName("labelExchange_2")
        self.gridLayout_IC.addWidget(self.labelExchange_2, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_IC.addWidget(self.label_17, 0, 2, 1, 1)
        self.underlyingText_IC = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.underlyingText_IC.setObjectName("underlyingText_IC")
        self.gridLayout_IC.addWidget(self.underlyingText_IC, 1, 0, 1, 1)
        self.comboBoxExchange_IC = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBoxExchange_IC.setToolTip("")
        self.comboBoxExchange_IC.setObjectName("comboBoxExchange_IC")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.gridLayout_IC.addWidget(self.comboBoxExchange_IC, 1, 1, 1, 1)
        self.comboBox_Expiry_IC = QtWidgets.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.comboBox_Expiry_IC.setFont(font)
        self.comboBox_Expiry_IC.setObjectName("comboBox_Expiry_IC")
        self.gridLayout_IC.addWidget(self.comboBox_Expiry_IC, 1, 2, 1, 1)
        self.groupBox_StrikePrice_IC = QtWidgets.QGroupBox(self.groupBox_IC)
        self.groupBox_StrikePrice_IC.setGeometry(QtCore.QRect(17, 140, 251, 51))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.groupBox_StrikePrice_IC.setFont(font)
        self.groupBox_StrikePrice_IC.setObjectName("groupBox_StrikePrice_IC")
        self.label_range_IC = QtWidgets.QLabel(self.groupBox_StrikePrice_IC)
        self.label_range_IC.setGeometry(QtCore.QRect(10, 30, 41, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_range_IC.setFont(font)
        self.label_range_IC.setObjectName("label_range_IC")
        self.label_Multiple_IC = QtWidgets.QLabel(self.groupBox_StrikePrice_IC)
        self.label_Multiple_IC.setGeometry(QtCore.QRect(120, 30, 51, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Multiple_IC.setFont(font)
        self.label_Multiple_IC.setObjectName("label_Multiple_IC")
        self.comboBox_StrikePriceRange_IC = QtWidgets.QComboBox(self.groupBox_StrikePrice_IC)
        self.comboBox_StrikePriceRange_IC.setGeometry(QtCore.QRect(50, 30, 51, 16))
        self.comboBox_StrikePriceRange_IC.setObjectName("comboBox_StrikePriceRange_IC")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceMultiple_IC = QtWidgets.QComboBox(self.groupBox_StrikePrice_IC)
        self.comboBox_StrikePriceMultiple_IC.setGeometry(QtCore.QRect(170, 30, 51, 16))
        self.comboBox_StrikePriceMultiple_IC.setObjectName("comboBox_StrikePriceMultiple_IC")
        self.comboBox_StrikePriceMultiple_IC.addItem("")
        self.comboBox_StrikePriceMultiple_IC.addItem("")
        self.comboBox_StrikePriceMultiple_IC.addItem("")
        self.comboBox_StrikePriceMultiple_IC.addItem("")
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_IC)
        self.layoutWidget_10.setGeometry(QtCore.QRect(19, 50, 121, 25))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.gridLayout_CallPut_IC = QtWidgets.QGridLayout(self.layoutWidget_10)
        self.gridLayout_CallPut_IC.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_CallPut_IC.setObjectName("gridLayout_CallPut_IC")
        self.radioButton_Call_IC = QtWidgets.QRadioButton(self.layoutWidget_10)
        self.radioButton_Call_IC.setChecked(True)
        self.radioButton_Call_IC.setObjectName("radioButton_Call_IC")
        self.gridLayout_CallPut_IC.addWidget(self.radioButton_Call_IC, 0, 0, 1, 1)
        self.radioButton_Put_IC = QtWidgets.QRadioButton(self.layoutWidget_10)
        self.radioButton_Put_IC.setObjectName("radioButton_Put_IC")
        self.gridLayout_CallPut_IC.addWidget(self.radioButton_Put_IC, 0, 1, 1, 1)
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox_IC)
        self.layoutWidget_11.setGeometry(QtCore.QRect(17, 220, 120, 25))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.gridLayout_CallPut_IC_2 = QtWidgets.QGridLayout(self.layoutWidget_11)
        self.gridLayout_CallPut_IC_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_CallPut_IC_2.setObjectName("gridLayout_CallPut_IC_2")
        self.radioButton_MktDataType_Frozen_IC = QtWidgets.QRadioButton(self.layoutWidget_11)
        self.radioButton_MktDataType_Frozen_IC.setChecked(True)
        self.radioButton_MktDataType_Frozen_IC.setObjectName("radioButton_MktDataType_Frozen_IC")
        self.gridLayout_CallPut_IC_2.addWidget(self.radioButton_MktDataType_Frozen_IC, 0, 0, 1, 1)
        self.radioButton_MktDataType_Live_IC = QtWidgets.QRadioButton(self.layoutWidget_11)
        self.radioButton_MktDataType_Live_IC.setObjectName("radioButton_MktDataType_Live_IC")
        self.gridLayout_CallPut_IC_2.addWidget(self.radioButton_MktDataType_Live_IC, 0, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_IC)
        self.line_3.setGeometry(QtCore.QRect(20, 40, 191, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_20 = QtWidgets.QLabel(self.groupBox_IC)
        self.label_20.setGeometry(QtCore.QRect(20, 200, 111, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_18 = QtWidgets.QLabel(self.page_ironCondor)
        self.label_18.setGeometry(QtCore.QRect(520, 360, 54, 17))
        self.label_18.setObjectName("label_18")
        self.stackedWidget.addWidget(self.page_ironCondor)
        MainPyOptionsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainPyOptionsWindow)
        font = QtGui.QFont()
        font.setFamily("Chandas")
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainPyOptionsWindow.setStatusBar(self.statusbar)
        self.actionIBToolbar = QtWidgets.QToolBar(MainPyOptionsWindow)
        self.actionIBToolbar.setMovable(False)
        self.actionIBToolbar.setFloatable(False)
        self.actionIBToolbar.setObjectName("actionIBToolbar")
        MainPyOptionsWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.actionIBToolbar)
        self.connectToIB = QtWidgets.QAction(MainPyOptionsWindow)
        self.connectToIB.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons/ConnectNo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons/ConnectEstablished.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons/ConnectCreating.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons/ConnectCreating.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.connectToIB.setIcon(icon1)
        self.connectToIB.setObjectName("connectToIB")
        self.actiontestIB = QtWidgets.QAction(MainPyOptionsWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../../local-packages/localUtilities/icons/py_pic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontestIB.setIcon(icon2)
        self.actiontestIB.setObjectName("actiontestIB")
        self.actiontestCheckableIB = QtWidgets.QAction(MainPyOptionsWindow)
        self.actiontestCheckableIB.setCheckable(True)
        self.actiontestCheckableIB.setChecked(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../../local-packages/localUtilities/icons/about.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontestCheckableIB.setIcon(icon3)
        self.actiontestCheckableIB.setObjectName("actiontestCheckableIB")
        self.actionIron_Condor = QtWidgets.QAction(MainPyOptionsWindow)
        self.actionIron_Condor.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Pictures/ironC.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/resources/icons/ironC.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionIron_Condor.setIcon(icon4)
        self.actionIron_Condor.setObjectName("actionIron_Condor")
        self.actionVertical_Spreads = QtWidgets.QAction(MainPyOptionsWindow)
        self.actionVertical_Spreads.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/resources/icons/download.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/resources/icons/download.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionVertical_Spreads.setIcon(icon5)
        self.actionVertical_Spreads.setObjectName("actionVertical_Spreads")
        self.actionIBToolbar.addAction(self.connectToIB)
        self.actionIBToolbar.addSeparator()
        self.actionIBToolbar.addAction(self.actionIron_Condor)
        self.actionIBToolbar.addAction(self.actionVertical_Spreads)

        self.retranslateUi(MainPyOptionsWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_Contracts.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainPyOptionsWindow)


        # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< def setup Ui --goes to here:<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

    # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< def retranslateUi -- from here:<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    def retranslateUi(self, MainPyOptionsWindow):
        _translate = QtCore.QCoreApplication.translate
        MainPyOptionsWindow.setWindowTitle(_translate("MainPyOptionsWindow", "IB Options"))
        self.groupBox_2.setTitle(_translate("MainPyOptionsWindow", "Underlying"))
        self.qualifyContracts.setText(_translate("MainPyOptionsWindow", "Qualify Contracts"))
        self.radioButton_Index.setText(_translate("MainPyOptionsWindow", "Index"))
        self.radioButton_Stock.setText(_translate("MainPyOptionsWindow", "Stock "))
        self.radioButton_Option.setText(_translate("MainPyOptionsWindow", "Option"))
        self.label_8.setText(_translate("MainPyOptionsWindow", "Underlying:"))
        self.labelExchange.setText(_translate("MainPyOptionsWindow", "Exchange:"))
        self.label.setText(_translate("MainPyOptionsWindow", "Expiry"))
        self.comboBoxExchange.setItemText(0, _translate("MainPyOptionsWindow", "CBOE"))
        self.comboBoxExchange.setItemText(1, _translate("MainPyOptionsWindow", "NASDAQ"))
        self.comboBoxExchange.setItemText(2, _translate("MainPyOptionsWindow", "SMART"))
        self.comboBoxExchange.setItemText(3, _translate("MainPyOptionsWindow", "ISLAND"))
        self.comboBoxExchange.setItemText(4, _translate("MainPyOptionsWindow", "NYSE"))
        self.comboBoxExchange.setItemText(5, _translate("MainPyOptionsWindow", "AMEX"))
        self.comboBoxExchange.setItemText(6, _translate("MainPyOptionsWindow", "IDEAL"))
        self.comboBoxExchange.setItemText(7, _translate("MainPyOptionsWindow", "PHLX"))
        self.groupBox_StrikePrice.setTitle(_translate("MainPyOptionsWindow", "Strike Price"))
        self.label_4.setText(_translate("MainPyOptionsWindow", "Range"))
        self.label_3.setText(_translate("MainPyOptionsWindow", "Multiple"))
        self.comboBox_StrikePriceRange.setItemText(0, _translate("MainPyOptionsWindow", "5"))
        self.comboBox_StrikePriceRange.setItemText(1, _translate("MainPyOptionsWindow", "10"))
        self.comboBox_StrikePriceRange.setItemText(2, _translate("MainPyOptionsWindow", "15"))
        self.comboBox_StrikePriceRange.setItemText(3, _translate("MainPyOptionsWindow", "20"))
        self.comboBox_StrikePriceRange.setItemText(4, _translate("MainPyOptionsWindow", "25"))
        self.comboBox_StrikePriceRange.setItemText(5, _translate("MainPyOptionsWindow", "30"))
        self.comboBox_StrikePriceRange.setItemText(6, _translate("MainPyOptionsWindow", "35"))
        self.comboBox_StrikePriceRange.setItemText(7, _translate("MainPyOptionsWindow", "40"))
        self.comboBox_StrikePriceRange.setItemText(8, _translate("MainPyOptionsWindow", "45"))
        self.comboBox_StrikePriceRange.setItemText(9, _translate("MainPyOptionsWindow", "50"))
        self.comboBox_StrikePriceMultiple.setItemText(0, _translate("MainPyOptionsWindow", "5"))
        self.comboBox_StrikePriceMultiple.setItemText(1, _translate("MainPyOptionsWindow", "10"))
        self.comboBox_StrikePriceMultiple.setItemText(2, _translate("MainPyOptionsWindow", "15"))
        self.comboBox_StrikePriceMultiple.setItemText(3, _translate("MainPyOptionsWindow", "20"))
        self.radioButton_Call.setText(_translate("MainPyOptionsWindow", "Call"))
        self.radioButton_Put.setText(_translate("MainPyOptionsWindow", "Put"))
        self.radioButton_MktDataType_Frozen.setText(_translate("MainPyOptionsWindow", "Frozen"))
        self.radioButton_MktDataType_Live.setText(_translate("MainPyOptionsWindow", "Live"))
        self.label_5.setText(_translate("MainPyOptionsWindow", "Market Data Type"))
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget_OptionGreeks.setSortingEnabled(False)
        self.label_2.setText(_translate("MainPyOptionsWindow", "The Greeks"))
        self.label_7.setText(_translate("MainPyOptionsWindow", "Contracts"))
        self.tabWidget_Contracts.setTabText(self.tabWidget_Contracts.indexOf(self.qualifyContracts_tab), _translate("MainPyOptionsWindow", "Option Contracts / Greeks"))
        self.label_6.setText(_translate("MainPyOptionsWindow", "Number Of Contracts"))
        self.pushButton_updateNumberOfContracts.setText(_translate("MainPyOptionsWindow", "Update"))
        self.label_9.setText(_translate("MainPyOptionsWindow", "Bull PUT Vertical Spread"))
        self.label_10.setText(_translate("MainPyOptionsWindow", "Bull CALL Vertical Spread "))
        self.tabWidget_Contracts.setTabText(self.tabWidget_Contracts.indexOf(self.bullSpread_tab), _translate("MainPyOptionsWindow", "Bull Spread"))
        self.tabWidget_Contracts.setTabText(self.tabWidget_Contracts.indexOf(self.tab3), _translate("MainPyOptionsWindow", "Tab3"))
        self.label_11.setText(_translate("MainPyOptionsWindow", "Underlying: "))
        self.label_12.setText(_translate("MainPyOptionsWindow", "Vertical Spreads "))
        self.label_14.setText(_translate("MainPyOptionsWindow", "Iron Condor"))
        self.groupBox_IC.setTitle(_translate("MainPyOptionsWindow", "Underlying"))
        self.qualifyIronCondor.setText(_translate("MainPyOptionsWindow", "Qualify Iron Condor"))
        self.radioButton_Index_IC.setText(_translate("MainPyOptionsWindow", "Index"))
        self.radioButton_Stock_IC.setText(_translate("MainPyOptionsWindow", "Stock "))
        self.radioButton_Option_IC.setText(_translate("MainPyOptionsWindow", "Option"))
        self.label_16.setText(_translate("MainPyOptionsWindow", "Underlying:"))
        self.labelExchange_2.setText(_translate("MainPyOptionsWindow", "Exchange:"))
        self.label_17.setText(_translate("MainPyOptionsWindow", "Expiry"))
        self.comboBoxExchange_IC.setItemText(0, _translate("MainPyOptionsWindow", "CBOE"))
        self.comboBoxExchange_IC.setItemText(1, _translate("MainPyOptionsWindow", "NASDAQ"))
        self.comboBoxExchange_IC.setItemText(2, _translate("MainPyOptionsWindow", "SMART"))
        self.comboBoxExchange_IC.setItemText(3, _translate("MainPyOptionsWindow", "ISLAND"))
        self.comboBoxExchange_IC.setItemText(4, _translate("MainPyOptionsWindow", "NYSE"))
        self.comboBoxExchange_IC.setItemText(5, _translate("MainPyOptionsWindow", "AMEX"))
        self.comboBoxExchange_IC.setItemText(6, _translate("MainPyOptionsWindow", "IDEAL"))
        self.comboBoxExchange_IC.setItemText(7, _translate("MainPyOptionsWindow", "PHLX"))
        self.groupBox_StrikePrice_IC.setTitle(_translate("MainPyOptionsWindow", "Strike Price"))
        self.label_range_IC.setText(_translate("MainPyOptionsWindow", "Range"))
        self.label_Multiple_IC.setText(_translate("MainPyOptionsWindow", "Multiple"))
        self.comboBox_StrikePriceRange_IC.setItemText(0, _translate("MainPyOptionsWindow", "5"))
        self.comboBox_StrikePriceRange_IC.setItemText(1, _translate("MainPyOptionsWindow", "10"))
        self.comboBox_StrikePriceRange_IC.setItemText(2, _translate("MainPyOptionsWindow", "15"))
        self.comboBox_StrikePriceRange_IC.setItemText(3, _translate("MainPyOptionsWindow", "20"))
        self.comboBox_StrikePriceRange_IC.setItemText(4, _translate("MainPyOptionsWindow", "25"))
        self.comboBox_StrikePriceRange_IC.setItemText(5, _translate("MainPyOptionsWindow", "30"))
        self.comboBox_StrikePriceRange_IC.setItemText(6, _translate("MainPyOptionsWindow", "35"))
        self.comboBox_StrikePriceRange_IC.setItemText(7, _translate("MainPyOptionsWindow", "40"))
        self.comboBox_StrikePriceRange_IC.setItemText(8, _translate("MainPyOptionsWindow", "45"))
        self.comboBox_StrikePriceRange_IC.setItemText(9, _translate("MainPyOptionsWindow", "50"))
        self.comboBox_StrikePriceMultiple_IC.setItemText(0, _translate("MainPyOptionsWindow", "5"))
        self.comboBox_StrikePriceMultiple_IC.setItemText(1, _translate("MainPyOptionsWindow", "10"))
        self.comboBox_StrikePriceMultiple_IC.setItemText(2, _translate("MainPyOptionsWindow", "15"))
        self.comboBox_StrikePriceMultiple_IC.setItemText(3, _translate("MainPyOptionsWindow", "20"))
        self.radioButton_Call_IC.setText(_translate("MainPyOptionsWindow", "Call"))
        self.radioButton_Put_IC.setText(_translate("MainPyOptionsWindow", "Put"))
        self.radioButton_MktDataType_Frozen_IC.setText(_translate("MainPyOptionsWindow", "Frozen"))
        self.radioButton_MktDataType_Live_IC.setText(_translate("MainPyOptionsWindow", "Live"))
        self.label_20.setText(_translate("MainPyOptionsWindow", "Market Data Type"))
        self.label_18.setText(_translate("MainPyOptionsWindow", "TextLabel"))
        self.actionIBToolbar.setWindowTitle(_translate("MainPyOptionsWindow", "toolBar_2"))
        self.connectToIB.setText(_translate("MainPyOptionsWindow", "Connect to IB "))
        self.connectToIB.setToolTip(_translate("MainPyOptionsWindow", "Connect to IB api"))
        self.actiontestIB.setText(_translate("MainPyOptionsWindow", "test"))
        self.actiontestIB.setToolTip(_translate("MainPyOptionsWindow", "Bark"))
        self.actiontestCheckableIB.setText(_translate("MainPyOptionsWindow", "testCheckable"))
        self.actiontestCheckableIB.setToolTip(_translate("MainPyOptionsWindow", "Meow"))
        self.actionIron_Condor.setText(_translate("MainPyOptionsWindow", "Iron Condor"))
        self.actionVertical_Spreads.setText(_translate("MainPyOptionsWindow", "Vertical Spreads"))
        # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< def retranslateUi -- to here:<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

        # ======== Below ========this is not part of the QT Creator for retranslateUi()===================

       # ===================  Set up Pages / Buttons Connectors    ===================

        # This is to set up the button connectors QT5
        buildVerticalSpreadViews.updateConnectVS(self, _translate)

        #create Vertical Spread / set up table trimmings - create tables Qt5
        buildVerticalSpreadViews.trimTable(self.tableWidget, self.tableWidget_OptionGreeks,
                                           self.tableWidget_BullCallSpread, self.tableWidget_BullPutSpread)

        #create the Iron Condor Page
        buildIronCondorViews.updateConnectIC(self, _translate)


import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainPyOptionsWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

