# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buildMainQT5View.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainPyOptionsWindow(object):
    def setupUi(self, MainPyOptionsWindow):
        MainPyOptionsWindow.setObjectName("MainPyOptionsWindow")
        MainPyOptionsWindow.resize(1494, 838)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icons/ib.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainPyOptionsWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainPyOptionsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 1461, 761))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_optionSpreads = QtWidgets.QWidget()
        self.page_optionSpreads.setObjectName("page_optionSpreads")
        self.tabWidget_Contracts = QtWidgets.QTabWidget(self.page_optionSpreads)
        self.tabWidget_Contracts.setGeometry(QtCore.QRect(20, 50, 1441, 711))
        self.tabWidget_Contracts.setObjectName("tabWidget_Contracts")
        self.qualifyContracts_tab = QtWidgets.QWidget()
        self.qualifyContracts_tab.setObjectName("qualifyContracts_tab")
        self.frame_2 = QtWidgets.QFrame(self.qualifyContracts_tab)
        self.frame_2.setGeometry(QtCore.QRect(20, 10, 361, 251))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(4)
        self.frame_2.setObjectName("frame_2")
        self.qualifyContracts = QtWidgets.QPushButton(self.frame_2)
        self.qualifyContracts.setGeometry(QtCore.QRect(220, 200, 111, 23))
        self.qualifyContracts.setObjectName("qualifyContracts")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setGeometry(QtCore.QRect(20, 30, 185, 30))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.radioButton_Index = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_Index.setChecked(True)
        self.radioButton_Index.setObjectName("radioButton_Index")
        self.radioButton_Stock = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_Stock.setObjectName("radioButton_Stock")
        self.radioButton_Option = QtWidgets.QRadioButton(self.splitter)
        self.radioButton_Option.setObjectName("radioButton_Option")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(18, 65, 327, 50))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.labelExchange = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.labelExchange.setFont(font)
        self.labelExchange.setWhatsThis("")
        self.labelExchange.setObjectName("labelExchange")
        self.gridLayout.addWidget(self.labelExchange, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.underlyingText = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.underlyingText.setObjectName("underlyingText")
        self.gridLayout.addWidget(self.underlyingText, 1, 0, 1, 1)
        self.comboBoxExchange = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBoxExchange.setToolTip("")
        self.comboBoxExchange.setObjectName("comboBoxExchange")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.comboBoxExchange.addItem("")
        self.gridLayout.addWidget(self.comboBoxExchange, 1, 1, 1, 1)
        self.comboBox_Expiry = QtWidgets.QComboBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.comboBox_Expiry.setFont(font)
        self.comboBox_Expiry.setObjectName("comboBox_Expiry")
        self.gridLayout.addWidget(self.comboBox_Expiry, 1, 2, 1, 1)
        self.groupBox_StrikePrice = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_StrikePrice.setGeometry(QtCore.QRect(17, 120, 251, 51))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.groupBox_StrikePrice.setFont(font)
        self.groupBox_StrikePrice.setObjectName("groupBox_StrikePrice")
        self.label_4 = QtWidgets.QLabel(self.groupBox_StrikePrice)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 41, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_StrikePrice)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 51, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_StrikePriceRange = QtWidgets.QComboBox(self.groupBox_StrikePrice)
        self.comboBox_StrikePriceRange.setGeometry(QtCore.QRect(50, 30, 51, 16))
        self.comboBox_StrikePriceRange.setObjectName("comboBox_StrikePriceRange")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceRange.addItem("")
        self.comboBox_StrikePriceMultiple = QtWidgets.QComboBox(self.groupBox_StrikePrice)
        self.comboBox_StrikePriceMultiple.setGeometry(QtCore.QRect(170, 30, 51, 16))
        self.comboBox_StrikePriceMultiple.setObjectName("comboBox_StrikePriceMultiple")
        self.comboBox_StrikePriceMultiple.addItem("")
        self.comboBox_StrikePriceMultiple.addItem("")
        self.comboBox_StrikePriceMultiple.addItem("")
        self.comboBox_StrikePriceMultiple.addItem("")
        self.layoutWidget_8 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_8.setGeometry(QtCore.QRect(17, 200, 163, 29))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.gridLayout_CallPut_2 = QtWidgets.QGridLayout(self.layoutWidget_8)
        self.gridLayout_CallPut_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_CallPut_2.setObjectName("gridLayout_CallPut_2")
        self.radioButton_MktDataType_Frozen = QtWidgets.QRadioButton(self.layoutWidget_8)
        self.radioButton_MktDataType_Frozen.setChecked(True)
        self.radioButton_MktDataType_Frozen.setObjectName("radioButton_MktDataType_Frozen")
        self.gridLayout_CallPut_2.addWidget(self.radioButton_MktDataType_Frozen, 0, 0, 1, 1)
        self.radioButton_MktDataType_Live = QtWidgets.QRadioButton(self.layoutWidget_8)
        self.radioButton_MktDataType_Live.setObjectName("radioButton_MktDataType_Live")
        self.gridLayout_CallPut_2.addWidget(self.radioButton_MktDataType_Live, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(20, 40, 191, 30))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 111, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_36 = QtWidgets.QLabel(self.frame_2)
        self.label_36.setGeometry(QtCore.QRect(10, 10, 201, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("font: 75 italic 14pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_36.setObjectName("label_36")
        self.tableWidget = QtWidgets.QTableWidget(self.qualifyContracts_tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 300, 461, 220))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(10)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(19)
        self.tableWidget.verticalHeader().setMinimumSectionSize(18)
        self.tableWidget_OptionGreeks = QtWidgets.QTableWidget(self.qualifyContracts_tab)
        self.tableWidget_OptionGreeks.setGeometry(QtCore.QRect(510, 300, 841, 331))
        self.tableWidget_OptionGreeks.setStyleSheet("")
        self.tableWidget_OptionGreeks.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_OptionGreeks.setAlternatingRowColors(True)
        self.tableWidget_OptionGreeks.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_OptionGreeks.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget_OptionGreeks.setRowCount(6)
        self.tableWidget_OptionGreeks.setColumnCount(9)
        self.tableWidget_OptionGreeks.setObjectName("tableWidget_OptionGreeks")
        self.tableWidget_OptionGreeks.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget_OptionGreeks.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_OptionGreeks.verticalHeader().setVisible(False)
        self.tableWidget_OptionGreeks.verticalHeader().setDefaultSectionSize(19)
        self.label_2 = QtWidgets.QLabel(self.qualifyContracts_tab)
        self.label_2.setGeometry(QtCore.QRect(520, 280, 101, 17))
        self.label_2.setStyleSheet("font: 75 italic 14pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.qualifyContracts_tab)
        self.label_7.setGeometry(QtCore.QRect(20, 280, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: 75 italic 14pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_7.setObjectName("label_7")
        self.frame = QtWidgets.QFrame(self.qualifyContracts_tab)
        self.frame.setGeometry(QtCore.QRect(430, 10, 371, 251))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(4)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 321, 204))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 5, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 3, 0, 1, 1)
        self.percentRange_30Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.percentRange_30Day.setObjectName("percentRange_30Day")
        self.gridLayout_3.addWidget(self.percentRange_30Day, 3, 1, 1, 1)
        self.percentRange_45Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.percentRange_45Day.setObjectName("percentRange_45Day")
        self.gridLayout_3.addWidget(self.percentRange_45Day, 3, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 4, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget)
        self.label_31.setStyleSheet("font: italic 12pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_31.setLineWidth(0)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 0, 1, 1, 1)
        self.dollarRangeUp_45Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.dollarRangeUp_45Day.setObjectName("dollarRangeUp_45Day")
        self.gridLayout_3.addWidget(self.dollarRangeUp_45Day, 5, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget)
        self.label_32.setStyleSheet("font: italic 12pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_32.setLineWidth(0)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setIndent(1)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 6, 0, 1, 1)
        self.dollarRangeDown_30Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.dollarRangeDown_30Day.setObjectName("dollarRangeDown_30Day")
        self.gridLayout_3.addWidget(self.dollarRangeDown_30Day, 6, 1, 1, 1)
        self.dollarRangeDown_45Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.dollarRangeDown_45Day.setObjectName("dollarRangeDown_45Day")
        self.gridLayout_3.addWidget(self.dollarRangeDown_45Day, 6, 2, 1, 1)
        self.dollarRange_45Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.dollarRange_45Day.setObjectName("dollarRange_45Day")
        self.gridLayout_3.addWidget(self.dollarRange_45Day, 4, 2, 1, 1)
        self.dollarRangeUp_30Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.dollarRangeUp_30Day.setObjectName("dollarRangeUp_30Day")
        self.gridLayout_3.addWidget(self.dollarRangeUp_30Day, 5, 1, 1, 1)
        self.VolPercent_30Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.VolPercent_30Day.setObjectName("VolPercent_30Day")
        self.gridLayout_3.addWidget(self.VolPercent_30Day, 1, 1, 1, 1)
        self.dollarRange_30Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.dollarRange_30Day.setObjectName("dollarRange_30Day")
        self.gridLayout_3.addWidget(self.dollarRange_30Day, 4, 1, 1, 1)
        self.volUSD_30Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.volUSD_30Day.setObjectName("volUSD_30Day")
        self.gridLayout_3.addWidget(self.volUSD_30Day, 2, 1, 1, 1)
        self.VolPercent_45Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.VolPercent_45Day.setObjectName("VolPercent_45Day")
        self.gridLayout_3.addWidget(self.VolPercent_45Day, 1, 2, 1, 1)
        self.volUSD_45Day = QtWidgets.QLineEdit(self.layoutWidget)
        self.volUSD_45Day.setObjectName("volUSD_45Day")
        self.gridLayout_3.addWidget(self.volUSD_45Day, 2, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setIndent(3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(10, 10, 211, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("font: 75 italic 14pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_29.setObjectName("label_29")
        self.frame_21 = QtWidgets.QFrame(self.qualifyContracts_tab)
        self.frame_21.setGeometry(QtCore.QRect(860, 10, 481, 251))
        self.frame_21.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setLineWidth(4)
        self.frame_21.setObjectName("frame_21")
        self.label_33 = QtWidgets.QLabel(self.frame_21)
        self.label_33.setGeometry(QtCore.QRect(10, 10, 201, 17))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("font: 75 italic 14pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_33.setObjectName("label_33")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_21)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 441, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 5, 0, 1, 1)
        self.totalOpenInterest = QtWidgets.QLineEdit(self.layoutWidget1)
        self.totalOpenInterest.setObjectName("totalOpenInterest")
        self.gridLayout_4.addWidget(self.totalOpenInterest, 6, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_4.addWidget(self.label_45, 4, 2, 1, 1)
        self.daysTExpiry = QtWidgets.QLabel(self.layoutWidget1)
        self.daysTExpiry.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.daysTExpiry.setObjectName("daysTExpiry")
        self.gridLayout_4.addWidget(self.daysTExpiry, 7, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 3, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 6, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_4.addWidget(self.label_44, 6, 2, 1, 1)
        self.historicVol = QtWidgets.QLineEdit(self.layoutWidget1)
        self.historicVol.setObjectName("historicVol")
        self.gridLayout_4.addWidget(self.historicVol, 3, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 4, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 1, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 1, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 3, 2, 1, 1)
        self.callOpenInterest = QtWidgets.QLineEdit(self.layoutWidget1)
        self.callOpenInterest.setObjectName("callOpenInterest")
        self.gridLayout_4.addWidget(self.callOpenInterest, 4, 1, 1, 1)
        self.callVolume = QtWidgets.QLineEdit(self.layoutWidget1)
        self.callVolume.setObjectName("callVolume")
        self.gridLayout_4.addWidget(self.callVolume, 4, 3, 1, 1)
        self.stockLast = QtWidgets.QLineEdit(self.layoutWidget1)
        self.stockLast.setObjectName("stockLast")
        self.gridLayout_4.addWidget(self.stockLast, 1, 1, 1, 1)
        self.stockClose = QtWidgets.QLineEdit(self.layoutWidget1)
        self.stockClose.setObjectName("stockClose")
        self.gridLayout_4.addWidget(self.stockClose, 1, 3, 1, 1)
        self.daysToExpiry = QtWidgets.QLineEdit(self.layoutWidget1)
        self.daysToExpiry.setObjectName("daysToExpiry")
        self.gridLayout_4.addWidget(self.daysToExpiry, 7, 3, 1, 1)
        self.putOpenInterest = QtWidgets.QLineEdit(self.layoutWidget1)
        self.putOpenInterest.setObjectName("putOpenInterest")
        self.gridLayout_4.addWidget(self.putOpenInterest, 5, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 5, 2, 1, 1)
        self.putVolume = QtWidgets.QLineEdit(self.layoutWidget1)
        self.putVolume.setObjectName("putVolume")
        self.gridLayout_4.addWidget(self.putVolume, 5, 3, 1, 1)
        self.totalVolume = QtWidgets.QLineEdit(self.layoutWidget1)
        self.totalVolume.setObjectName("totalVolume")
        self.gridLayout_4.addWidget(self.totalVolume, 6, 3, 1, 1)
        self.impliedVol = QtWidgets.QLineEdit(self.layoutWidget1)
        self.impliedVol.setObjectName("impliedVol")
        self.gridLayout_4.addWidget(self.impliedVol, 3, 1, 1, 1)
        self.tabWidget_Contracts.addTab(self.qualifyContracts_tab, "")
        self.bullSpread_tab = QtWidgets.QWidget()
        self.bullSpread_tab.setObjectName("bullSpread_tab")
        self.tableWidget_BullCallSpread = QtWidgets.QTableWidget(self.bullSpread_tab)
        self.tableWidget_BullCallSpread.setGeometry(QtCore.QRect(20, 90, 521, 571))
        self.tableWidget_BullCallSpread.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_BullCallSpread.setAlternatingRowColors(True)
        self.tableWidget_BullCallSpread.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_BullCallSpread.setRowCount(5)
        self.tableWidget_BullCallSpread.setColumnCount(4)
        self.tableWidget_BullCallSpread.setObjectName("tableWidget_BullCallSpread")
        self.tableWidget_BullCallSpread.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_BullCallSpread.horizontalHeader().setMinimumSectionSize(11)
        self.tableWidget_BullCallSpread.verticalHeader().setDefaultSectionSize(25)
        self.layoutWidget_9 = QtWidgets.QWidget(self.bullSpread_tab)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 10, 260, 28))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.spinBox_numberOfContracts_BullSpread = QtWidgets.QSpinBox(self.layoutWidget_9)
        self.spinBox_numberOfContracts_BullSpread.setMinimum(1)
        self.spinBox_numberOfContracts_BullSpread.setMaximum(15)
        self.spinBox_numberOfContracts_BullSpread.setObjectName("spinBox_numberOfContracts_BullSpread")
        self.horizontalLayout.addWidget(self.spinBox_numberOfContracts_BullSpread)
        self.pushButton_updateNumberOfContracts_BullSpread = QtWidgets.QPushButton(self.layoutWidget_9)
        self.pushButton_updateNumberOfContracts_BullSpread.setObjectName("pushButton_updateNumberOfContracts_BullSpread")
        self.horizontalLayout.addWidget(self.pushButton_updateNumberOfContracts_BullSpread)
        self.label_9 = QtWidgets.QLabel(self.bullSpread_tab)
        self.label_9.setGeometry(QtCore.QRect(640, 70, 411, 20))
        self.label_9.setStyleSheet("font: 75 italic 16pt \"aakar\";\n"
"color: rgb(32, 74, 135);")
        self.label_9.setObjectName("label_9")
        self.tableWidget_BullPutSpread = QtWidgets.QTableWidget(self.bullSpread_tab)
        self.tableWidget_BullPutSpread.setGeometry(QtCore.QRect(610, 90, 521, 571))
        self.tableWidget_BullPutSpread.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_BullPutSpread.setAlternatingRowColors(True)
        self.tableWidget_BullPutSpread.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_BullPutSpread.setRowCount(5)
        self.tableWidget_BullPutSpread.setColumnCount(4)
        self.tableWidget_BullPutSpread.setObjectName("tableWidget_BullPutSpread")
        self.tableWidget_BullPutSpread.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_BullPutSpread.horizontalHeader().setMinimumSectionSize(11)
        self.tableWidget_BullPutSpread.verticalHeader().setDefaultSectionSize(25)
        self.label_10 = QtWidgets.QLabel(self.bullSpread_tab)
        self.label_10.setGeometry(QtCore.QRect(20, 70, 261, 20))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("font: 75 italic 16pt \"aakar\";\n"
"color: rgb(32, 74, 135);")
        self.label_10.setObjectName("label_10")
        self.line = QtWidgets.QFrame(self.bullSpread_tab)
        self.line.setGeometry(QtCore.QRect(20, 35, 271, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.tabWidget_Contracts.addTab(self.bullSpread_tab, "")
        self.bearSpreads_tab = QtWidgets.QWidget()
        self.bearSpreads_tab.setObjectName("bearSpreads_tab")
        self.line_4 = QtWidgets.QFrame(self.bearSpreads_tab)
        self.line_4.setGeometry(QtCore.QRect(20, 40, 271, 20))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.tableWidget_BearPutSpread = QtWidgets.QTableWidget(self.bearSpreads_tab)
        self.tableWidget_BearPutSpread.setGeometry(QtCore.QRect(610, 80, 521, 571))
        self.tableWidget_BearPutSpread.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_BearPutSpread.setAlternatingRowColors(True)
        self.tableWidget_BearPutSpread.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_BearPutSpread.setRowCount(5)
        self.tableWidget_BearPutSpread.setColumnCount(4)
        self.tableWidget_BearPutSpread.setObjectName("tableWidget_BearPutSpread")
        self.tableWidget_BearPutSpread.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_BearPutSpread.horizontalHeader().setMinimumSectionSize(11)
        self.tableWidget_BearPutSpread.verticalHeader().setDefaultSectionSize(25)
        self.pushButton_updateNumberOfContracts_BearSpread = QtWidgets.QPushButton(self.bearSpreads_tab)
        self.pushButton_updateNumberOfContracts_BearSpread.setGeometry(QtCore.QRect(201, 10, 80, 25))
        self.pushButton_updateNumberOfContracts_BearSpread.setObjectName("pushButton_updateNumberOfContracts_BearSpread")
        self.tableWidget_BearCallSpread = QtWidgets.QTableWidget(self.bearSpreads_tab)
        self.tableWidget_BearCallSpread.setGeometry(QtCore.QRect(20, 80, 521, 571))
        self.tableWidget_BearCallSpread.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_BearCallSpread.setAlternatingRowColors(True)
        self.tableWidget_BearCallSpread.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_BearCallSpread.setRowCount(5)
        self.tableWidget_BearCallSpread.setColumnCount(4)
        self.tableWidget_BearCallSpread.setObjectName("tableWidget_BearCallSpread")
        self.tableWidget_BearCallSpread.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget_BearCallSpread.horizontalHeader().setMinimumSectionSize(11)
        self.tableWidget_BearCallSpread.verticalHeader().setDefaultSectionSize(25)
        self.label_19 = QtWidgets.QLabel(self.bearSpreads_tab)
        self.label_19.setGeometry(QtCore.QRect(20, 60, 261, 20))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("font: 75 italic 16pt \"aakar\";\n"
"color: rgb(32, 74, 135);")
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.bearSpreads_tab)
        self.label_21.setGeometry(QtCore.QRect(23, 10, 121, 26))
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.bearSpreads_tab)
        self.label_23.setGeometry(QtCore.QRect(640, 60, 411, 20))
        self.label_23.setStyleSheet("font: 75 italic 16pt \"aakar\";\n"
"color: rgb(32, 74, 135);")
        self.label_23.setObjectName("label_23")
        self.spinBox_numberOfContracts_BearSpread = QtWidgets.QSpinBox(self.bearSpreads_tab)
        self.spinBox_numberOfContracts_BearSpread.setGeometry(QtCore.QRect(150, 10, 45, 26))
        self.spinBox_numberOfContracts_BearSpread.setMinimum(1)
        self.spinBox_numberOfContracts_BearSpread.setMaximum(15)
        self.spinBox_numberOfContracts_BearSpread.setObjectName("spinBox_numberOfContracts_BearSpread")
        self.tabWidget_Contracts.addTab(self.bearSpreads_tab, "")
        self.layoutWidget2 = QtWidgets.QWidget(self.page_optionSpreads)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 10, 341, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setStyleSheet("font: 75 italic 12pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.lineEdit_underlying = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_underlying.setReadOnly(True)
        self.lineEdit_underlying.setObjectName("lineEdit_underlying")
        self.horizontalLayout_2.addWidget(self.lineEdit_underlying)
        self.label_12 = QtWidgets.QLabel(self.page_optionSpreads)
        self.label_12.setGeometry(QtCore.QRect(1120, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("font: 75 italic 20pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_optionSpreads)
        self.label_13.setGeometry(QtCore.QRect(1040, 10, 71, 41))
        self.label_13.setStyleSheet("image: url(:/resources/icons/download.ico);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_optionSpreads)
        self.page_ironCondor = QtWidgets.QWidget()
        self.page_ironCondor.setObjectName("page_ironCondor")
        self.label_15 = QtWidgets.QLabel(self.page_ironCondor)
        self.label_15.setGeometry(QtCore.QRect(830, 10, 71, 41))
        self.label_15.setStyleSheet("image: url(:/resources/icons/ironC.ico);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.page_ironCondor)
        self.label_14.setGeometry(QtCore.QRect(910, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("font: 75 italic 20pt \"Ubuntu Mono\";\n"
"color: rgb(32, 74, 135);")
        self.label_14.setObjectName("label_14")
        self.groupBox_IC = QtWidgets.QGroupBox(self.page_ironCondor)
        self.groupBox_IC.setGeometry(QtCore.QRect(20, 10, 291, 261))
        self.groupBox_IC.setObjectName("groupBox_IC")
        self.qualifyIronCondor = QtWidgets.QPushButton(self.groupBox_IC)
        self.qualifyIronCondor.setGeometry(QtCore.QRect(160, 220, 121, 23))
        self.qualifyIronCondor.setObjectName("qualifyIronCondor")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox_IC)
        self.splitter_2.setGeometry(QtCore.QRect(20, 30, 185, 17))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.radioButton_Index_IC = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_Index_IC.setChecked(True)
        self.radioButton_Index_IC.setObjectName("radioButton_Index_IC")
        self.radioButton_Stock_IC = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_Stock_IC.setObjectName("radioButton_Stock_IC")
        self.radioButton_Option_IC = QtWidgets.QRadioButton(self.splitter_2)
        self.radioButton_Option_IC.setObjectName("radioButton_Option_IC")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_IC)
        self.layoutWidget_3.setGeometry(QtCore.QRect(17, 81, 250, 50))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_IC = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_IC.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_IC.setObjectName("gridLayout_IC")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(True)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_IC.addWidget(self.label_16, 0, 0, 1, 1)
        self.labelExchange_2 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.labelExchange_2.setFont(font)
        self.labelExchange_2.setWhatsThis("")
        self.labelExchange_2.setObjectName("labelExchange_2")
        self.gridLayout_IC.addWidget(self.labelExchange_2, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_IC.addWidget(self.label_17, 0, 2, 1, 1)
        self.underlyingText_IC = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.underlyingText_IC.setObjectName("underlyingText_IC")
        self.gridLayout_IC.addWidget(self.underlyingText_IC, 1, 0, 1, 1)
        self.comboBoxExchange_IC = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBoxExchange_IC.setToolTip("")
        self.comboBoxExchange_IC.setObjectName("comboBoxExchange_IC")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.comboBoxExchange_IC.addItem("")
        self.gridLayout_IC.addWidget(self.comboBoxExchange_IC, 1, 1, 1, 1)
        self.comboBox_Expiry_IC = QtWidgets.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(10)
        self.comboBox_Expiry_IC.setFont(font)
        self.comboBox_Expiry_IC.setObjectName("comboBox_Expiry_IC")
        self.gridLayout_IC.addWidget(self.comboBox_Expiry_IC, 1, 2, 1, 1)
        self.groupBox_StrikePrice_IC = QtWidgets.QGroupBox(self.groupBox_IC)
        self.groupBox_StrikePrice_IC.setGeometry(QtCore.QRect(17, 140, 251, 51))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.groupBox_StrikePrice_IC.setFont(font)
        self.groupBox_StrikePrice_IC.setObjectName("groupBox_StrikePrice_IC")
        self.label_range_IC = QtWidgets.QLabel(self.groupBox_StrikePrice_IC)
        self.label_range_IC.setGeometry(QtCore.QRect(10, 30, 41, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_range_IC.setFont(font)
        self.label_range_IC.setObjectName("label_range_IC")
        self.label_Multiple_IC = QtWidgets.QLabel(self.groupBox_StrikePrice_IC)
        self.label_Multiple_IC.setGeometry(QtCore.QRect(120, 30, 51, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_Multiple_IC.setFont(font)
        self.label_Multiple_IC.setObjectName("label_Multiple_IC")
        self.comboBox_StrikePriceRange_IC = QtWidgets.QComboBox(self.groupBox_StrikePrice_IC)
        self.comboBox_StrikePriceRange_IC.setGeometry(QtCore.QRect(50, 30, 51, 16))
        self.comboBox_StrikePriceRange_IC.setObjectName("comboBox_StrikePriceRange_IC")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceRange_IC.addItem("")
        self.comboBox_StrikePriceMultiple_IC = QtWidgets.QComboBox(self.groupBox_StrikePrice_IC)
        self.comboBox_StrikePriceMultiple_IC.setGeometry(QtCore.QRect(170, 30, 51, 16))
        self.comboBox_StrikePriceMultiple_IC.setObjectName("comboBox_StrikePriceMultiple_IC")
        self.comboBox_StrikePriceMultiple_IC.addItem("")
        self.comboBox_StrikePriceMultiple_IC.addItem("")
        self.comboBox_StrikePriceMultiple_IC.addItem("")
        self.comboBox_StrikePriceMultiple_IC.addItem("")
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_IC)
        self.layoutWidget_10.setGeometry(QtCore.QRect(19, 50, 121, 25))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.gridLayout_CallPut_IC = QtWidgets.QGridLayout(self.layoutWidget_10)
        self.gridLayout_CallPut_IC.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_CallPut_IC.setObjectName("gridLayout_CallPut_IC")
        self.radioButton_Call_IC = QtWidgets.QRadioButton(self.layoutWidget_10)
        self.radioButton_Call_IC.setChecked(True)
        self.radioButton_Call_IC.setObjectName("radioButton_Call_IC")
        self.gridLayout_CallPut_IC.addWidget(self.radioButton_Call_IC, 0, 0, 1, 1)
        self.radioButton_Put_IC = QtWidgets.QRadioButton(self.layoutWidget_10)
        self.radioButton_Put_IC.setObjectName("radioButton_Put_IC")
        self.gridLayout_CallPut_IC.addWidget(self.radioButton_Put_IC, 0, 1, 1, 1)
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox_IC)
        self.layoutWidget_11.setGeometry(QtCore.QRect(17, 220, 120, 25))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.gridLayout_CallPut_IC_2 = QtWidgets.QGridLayout(self.layoutWidget_11)
        self.gridLayout_CallPut_IC_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_CallPut_IC_2.setObjectName("gridLayout_CallPut_IC_2")
        self.radioButton_MktDataType_Frozen_IC = QtWidgets.QRadioButton(self.layoutWidget_11)
        self.radioButton_MktDataType_Frozen_IC.setChecked(True)
        self.radioButton_MktDataType_Frozen_IC.setObjectName("radioButton_MktDataType_Frozen_IC")
        self.gridLayout_CallPut_IC_2.addWidget(self.radioButton_MktDataType_Frozen_IC, 0, 0, 1, 1)
        self.radioButton_MktDataType_Live_IC = QtWidgets.QRadioButton(self.layoutWidget_11)
        self.radioButton_MktDataType_Live_IC.setObjectName("radioButton_MktDataType_Live_IC")
        self.gridLayout_CallPut_IC_2.addWidget(self.radioButton_MktDataType_Live_IC, 0, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_IC)
        self.line_3.setGeometry(QtCore.QRect(20, 40, 191, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_20 = QtWidgets.QLabel(self.groupBox_IC)
        self.label_20.setGeometry(QtCore.QRect(20, 200, 111, 17))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_18 = QtWidgets.QLabel(self.page_ironCondor)
        self.label_18.setGeometry(QtCore.QRect(520, 360, 54, 17))
        self.label_18.setObjectName("label_18")
        self.stackedWidget.addWidget(self.page_ironCondor)
        MainPyOptionsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainPyOptionsWindow)
        font = QtGui.QFont()
        font.setFamily("Chandas")
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainPyOptionsWindow.setStatusBar(self.statusbar)
        self.actionIBToolbar = QtWidgets.QToolBar(MainPyOptionsWindow)
        self.actionIBToolbar.setMovable(False)
        self.actionIBToolbar.setFloatable(False)
        self.actionIBToolbar.setObjectName("actionIBToolbar")
        MainPyOptionsWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.actionIBToolbar)
        self.connectToIB = QtWidgets.QAction(MainPyOptionsWindow)
        self.connectToIB.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons/ConnectNo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons/ConnectEstablished.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons/ConnectCreating.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/resources/icons/ConnectCreating.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.connectToIB.setIcon(icon1)
        self.connectToIB.setObjectName("connectToIB")
        self.actiontestIB = QtWidgets.QAction(MainPyOptionsWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../../../../../local-packages/localUtilities/icons/py_pic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontestIB.setIcon(icon2)
        self.actiontestIB.setObjectName("actiontestIB")
        self.actiontestCheckableIB = QtWidgets.QAction(MainPyOptionsWindow)
        self.actiontestCheckableIB.setCheckable(True)
        self.actiontestCheckableIB.setChecked(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../../../../../local-packages/localUtilities/icons/about.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actiontestCheckableIB.setIcon(icon3)
        self.actiontestCheckableIB.setObjectName("actiontestCheckableIB")
        self.actionIron_Condor = QtWidgets.QAction(MainPyOptionsWindow)
        self.actionIron_Condor.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Pictures/ironC.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/resources/icons/ironC.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionIron_Condor.setIcon(icon4)
        self.actionIron_Condor.setObjectName("actionIron_Condor")
        self.actionVertical_Spreads = QtWidgets.QAction(MainPyOptionsWindow)
        self.actionVertical_Spreads.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../../../.designer/backup/resources/icons/download.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/resources/icons/download.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionVertical_Spreads.setIcon(icon5)
        self.actionVertical_Spreads.setObjectName("actionVertical_Spreads")
        self.actionIBToolbar.addAction(self.connectToIB)
        self.actionIBToolbar.addSeparator()
        self.actionIBToolbar.addAction(self.actionIron_Condor)
        self.actionIBToolbar.addAction(self.actionVertical_Spreads)

        self.retranslateUi(MainPyOptionsWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_Contracts.setCurrentIndex(2)
        self.tableWidget.cellClicked['int','int'].connect(self.tableWidget_OptionGreeks.selectRow)
        QtCore.QMetaObject.connectSlotsByName(MainPyOptionsWindow)
        MainPyOptionsWindow.setTabOrder(self.underlyingText, self.comboBoxExchange)
        MainPyOptionsWindow.setTabOrder(self.comboBoxExchange, self.comboBox_Expiry)
        MainPyOptionsWindow.setTabOrder(self.comboBox_Expiry, self.comboBox_StrikePriceRange)
        MainPyOptionsWindow.setTabOrder(self.comboBox_StrikePriceRange, self.comboBox_StrikePriceMultiple)
        MainPyOptionsWindow.setTabOrder(self.comboBox_StrikePriceMultiple, self.qualifyContracts)
        MainPyOptionsWindow.setTabOrder(self.qualifyContracts, self.radioButton_Index)
        MainPyOptionsWindow.setTabOrder(self.radioButton_Index, self.radioButton_Stock)
        MainPyOptionsWindow.setTabOrder(self.radioButton_Stock, self.radioButton_Option)
        MainPyOptionsWindow.setTabOrder(self.radioButton_Option, self.radioButton_MktDataType_Live)
        MainPyOptionsWindow.setTabOrder(self.radioButton_MktDataType_Live, self.tabWidget_Contracts)
        MainPyOptionsWindow.setTabOrder(self.tabWidget_Contracts, self.tableWidget)
        MainPyOptionsWindow.setTabOrder(self.tableWidget, self.tableWidget_OptionGreeks)
        MainPyOptionsWindow.setTabOrder(self.tableWidget_OptionGreeks, self.tableWidget_BullCallSpread)
        MainPyOptionsWindow.setTabOrder(self.tableWidget_BullCallSpread, self.spinBox_numberOfContracts_BullSpread)
        MainPyOptionsWindow.setTabOrder(self.spinBox_numberOfContracts_BullSpread, self.pushButton_updateNumberOfContracts_BullSpread)
        MainPyOptionsWindow.setTabOrder(self.pushButton_updateNumberOfContracts_BullSpread, self.tableWidget_BullPutSpread)
        MainPyOptionsWindow.setTabOrder(self.tableWidget_BullPutSpread, self.lineEdit_underlying)
        MainPyOptionsWindow.setTabOrder(self.lineEdit_underlying, self.qualifyIronCondor)
        MainPyOptionsWindow.setTabOrder(self.qualifyIronCondor, self.radioButton_Index_IC)
        MainPyOptionsWindow.setTabOrder(self.radioButton_Index_IC, self.radioButton_MktDataType_Frozen)
        MainPyOptionsWindow.setTabOrder(self.radioButton_MktDataType_Frozen, self.radioButton_Stock_IC)
        MainPyOptionsWindow.setTabOrder(self.radioButton_Stock_IC, self.radioButton_Option_IC)
        MainPyOptionsWindow.setTabOrder(self.radioButton_Option_IC, self.underlyingText_IC)
        MainPyOptionsWindow.setTabOrder(self.underlyingText_IC, self.comboBoxExchange_IC)
        MainPyOptionsWindow.setTabOrder(self.comboBoxExchange_IC, self.comboBox_Expiry_IC)
        MainPyOptionsWindow.setTabOrder(self.comboBox_Expiry_IC, self.comboBox_StrikePriceRange_IC)
        MainPyOptionsWindow.setTabOrder(self.comboBox_StrikePriceRange_IC, self.comboBox_StrikePriceMultiple_IC)
        MainPyOptionsWindow.setTabOrder(self.comboBox_StrikePriceMultiple_IC, self.radioButton_Call_IC)
        MainPyOptionsWindow.setTabOrder(self.radioButton_Call_IC, self.radioButton_Put_IC)
        MainPyOptionsWindow.setTabOrder(self.radioButton_Put_IC, self.radioButton_MktDataType_Frozen_IC)
        MainPyOptionsWindow.setTabOrder(self.radioButton_MktDataType_Frozen_IC, self.radioButton_MktDataType_Live_IC)

    def retranslateUi(self, MainPyOptionsWindow):
        _translate = QtCore.QCoreApplication.translate
        MainPyOptionsWindow.setWindowTitle(_translate("MainPyOptionsWindow", "IB Options"))
        self.qualifyContracts.setText(_translate("MainPyOptionsWindow", "Qualify Contracts"))
        self.radioButton_Index.setText(_translate("MainPyOptionsWindow", "Index"))
        self.radioButton_Stock.setText(_translate("MainPyOptionsWindow", "Stock "))
        self.radioButton_Option.setText(_translate("MainPyOptionsWindow", "Option"))
        self.label_8.setText(_translate("MainPyOptionsWindow", "Underlying:"))
        self.labelExchange.setText(_translate("MainPyOptionsWindow", "Exchange:"))
        self.label.setText(_translate("MainPyOptionsWindow", "Expiry"))
        self.comboBoxExchange.setItemText(0, _translate("MainPyOptionsWindow", "CBOE"))
        self.comboBoxExchange.setItemText(1, _translate("MainPyOptionsWindow", "NASDAQ"))
        self.comboBoxExchange.setItemText(2, _translate("MainPyOptionsWindow", "SMART"))
        self.comboBoxExchange.setItemText(3, _translate("MainPyOptionsWindow", "ISLAND"))
        self.comboBoxExchange.setItemText(4, _translate("MainPyOptionsWindow", "NYSE"))
        self.comboBoxExchange.setItemText(5, _translate("MainPyOptionsWindow", "AMEX"))
        self.comboBoxExchange.setItemText(6, _translate("MainPyOptionsWindow", "IDEAL"))
        self.comboBoxExchange.setItemText(7, _translate("MainPyOptionsWindow", "PHLX"))
        self.groupBox_StrikePrice.setTitle(_translate("MainPyOptionsWindow", "Strike Price"))
        self.label_4.setText(_translate("MainPyOptionsWindow", "Range"))
        self.label_3.setText(_translate("MainPyOptionsWindow", "Multiple"))
        self.comboBox_StrikePriceRange.setItemText(0, _translate("MainPyOptionsWindow", "5"))
        self.comboBox_StrikePriceRange.setItemText(1, _translate("MainPyOptionsWindow", "10"))
        self.comboBox_StrikePriceRange.setItemText(2, _translate("MainPyOptionsWindow", "15"))
        self.comboBox_StrikePriceRange.setItemText(3, _translate("MainPyOptionsWindow", "20"))
        self.comboBox_StrikePriceRange.setItemText(4, _translate("MainPyOptionsWindow", "25"))
        self.comboBox_StrikePriceRange.setItemText(5, _translate("MainPyOptionsWindow", "30"))
        self.comboBox_StrikePriceRange.setItemText(6, _translate("MainPyOptionsWindow", "35"))
        self.comboBox_StrikePriceRange.setItemText(7, _translate("MainPyOptionsWindow", "40"))
        self.comboBox_StrikePriceRange.setItemText(8, _translate("MainPyOptionsWindow", "45"))
        self.comboBox_StrikePriceRange.setItemText(9, _translate("MainPyOptionsWindow", "50"))
        self.comboBox_StrikePriceMultiple.setItemText(0, _translate("MainPyOptionsWindow", "5"))
        self.comboBox_StrikePriceMultiple.setItemText(1, _translate("MainPyOptionsWindow", "10"))
        self.comboBox_StrikePriceMultiple.setItemText(2, _translate("MainPyOptionsWindow", "15"))
        self.comboBox_StrikePriceMultiple.setItemText(3, _translate("MainPyOptionsWindow", "20"))
        self.radioButton_MktDataType_Frozen.setText(_translate("MainPyOptionsWindow", "Frozen"))
        self.radioButton_MktDataType_Live.setText(_translate("MainPyOptionsWindow", "Live"))
        self.label_5.setText(_translate("MainPyOptionsWindow", "Market Data Type"))
        self.label_36.setText(_translate("MainPyOptionsWindow", "Underlying"))
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget_OptionGreeks.setSortingEnabled(True)
        self.label_2.setText(_translate("MainPyOptionsWindow", "The Greeks"))
        self.label_7.setText(_translate("MainPyOptionsWindow", "Contracts"))
        self.label_22.setText(_translate("MainPyOptionsWindow", "Volatility USD$"))
        self.label_27.setText(_translate("MainPyOptionsWindow", "$ Range (+) Up"))
        self.label_25.setText(_translate("MainPyOptionsWindow", "% Range +/-"))
        self.label_26.setText(_translate("MainPyOptionsWindow", "$ Range +/-"))
        self.label_31.setText(_translate("MainPyOptionsWindow", "30 Days"))
        self.label_32.setText(_translate("MainPyOptionsWindow", "45 Days"))
        self.label_28.setText(_translate("MainPyOptionsWindow", "$ Range (-) Down"))
        self.label_30.setText(_translate("MainPyOptionsWindow", "Volatiltiy %"))
        self.label_29.setText(_translate("MainPyOptionsWindow", "Projected Volatility"))
        self.label_33.setText(_translate("MainPyOptionsWindow", "Underlying Details"))
        self.label_37.setText(_translate("MainPyOptionsWindow", "Put Open Interest"))
        self.label_45.setText(_translate("MainPyOptionsWindow", "Call Volume"))
        self.daysTExpiry.setText(_translate("MainPyOptionsWindow", "Days to Expiry"))
        self.label_39.setText(_translate("MainPyOptionsWindow", "Implied Vol. "))
        self.label_42.setText(_translate("MainPyOptionsWindow", "Total Open Interest"))
        self.label_44.setText(_translate("MainPyOptionsWindow", "Total Volume"))
        self.label_40.setText(_translate("MainPyOptionsWindow", "Call Open Interest"))
        self.label_35.setText(_translate("MainPyOptionsWindow", "Stock Close"))
        self.label_34.setText(_translate("MainPyOptionsWindow", "Stock Last"))
        self.label_38.setText(_translate("MainPyOptionsWindow", "Historic Vol."))
        self.label_41.setText(_translate("MainPyOptionsWindow", "Put Volume"))
        self.tabWidget_Contracts.setTabText(self.tabWidget_Contracts.indexOf(self.qualifyContracts_tab), _translate("MainPyOptionsWindow", "Option Contracts / Greeks"))
        self.label_6.setText(_translate("MainPyOptionsWindow", "Number Of Contracts"))
        self.pushButton_updateNumberOfContracts_BullSpread.setText(_translate("MainPyOptionsWindow", "Update"))
        self.label_9.setText(_translate("MainPyOptionsWindow", "Bull PUT Vertical Spread - Credit Spread"))
        self.label_10.setText(_translate("MainPyOptionsWindow", "Bull CALL Vertical Spread "))
        self.tabWidget_Contracts.setTabText(self.tabWidget_Contracts.indexOf(self.bullSpread_tab), _translate("MainPyOptionsWindow", "Bull Spreads"))
        self.pushButton_updateNumberOfContracts_BearSpread.setText(_translate("MainPyOptionsWindow", "Update"))
        self.label_19.setText(_translate("MainPyOptionsWindow", "Bear CALL Vertical Spread "))
        self.label_21.setText(_translate("MainPyOptionsWindow", "Number Of Contracts"))
        self.label_23.setText(_translate("MainPyOptionsWindow", "Bear PUT Vertical Spread - Credit Spread"))
        self.tabWidget_Contracts.setTabText(self.tabWidget_Contracts.indexOf(self.bearSpreads_tab), _translate("MainPyOptionsWindow", "Bear Spreads"))
        self.label_11.setText(_translate("MainPyOptionsWindow", "Underlying: "))
        self.label_12.setText(_translate("MainPyOptionsWindow", "Vertical Spreads "))
        self.label_14.setText(_translate("MainPyOptionsWindow", "Iron Condor"))
        self.groupBox_IC.setTitle(_translate("MainPyOptionsWindow", "Underlying"))
        self.qualifyIronCondor.setText(_translate("MainPyOptionsWindow", "Qualify Iron Condor"))
        self.radioButton_Index_IC.setText(_translate("MainPyOptionsWindow", "Index"))
        self.radioButton_Stock_IC.setText(_translate("MainPyOptionsWindow", "Stock "))
        self.radioButton_Option_IC.setText(_translate("MainPyOptionsWindow", "Option"))
        self.label_16.setText(_translate("MainPyOptionsWindow", "Underlying:"))
        self.labelExchange_2.setText(_translate("MainPyOptionsWindow", "Exchange:"))
        self.label_17.setText(_translate("MainPyOptionsWindow", "Expiry"))
        self.comboBoxExchange_IC.setItemText(0, _translate("MainPyOptionsWindow", "CBOE"))
        self.comboBoxExchange_IC.setItemText(1, _translate("MainPyOptionsWindow", "NASDAQ"))
        self.comboBoxExchange_IC.setItemText(2, _translate("MainPyOptionsWindow", "SMART"))
        self.comboBoxExchange_IC.setItemText(3, _translate("MainPyOptionsWindow", "ISLAND"))
        self.comboBoxExchange_IC.setItemText(4, _translate("MainPyOptionsWindow", "NYSE"))
        self.comboBoxExchange_IC.setItemText(5, _translate("MainPyOptionsWindow", "AMEX"))
        self.comboBoxExchange_IC.setItemText(6, _translate("MainPyOptionsWindow", "IDEAL"))
        self.comboBoxExchange_IC.setItemText(7, _translate("MainPyOptionsWindow", "PHLX"))
        self.groupBox_StrikePrice_IC.setTitle(_translate("MainPyOptionsWindow", "Strike Price"))
        self.label_range_IC.setText(_translate("MainPyOptionsWindow", "Range"))
        self.label_Multiple_IC.setText(_translate("MainPyOptionsWindow", "Multiple"))
        self.comboBox_StrikePriceRange_IC.setItemText(0, _translate("MainPyOptionsWindow", "5"))
        self.comboBox_StrikePriceRange_IC.setItemText(1, _translate("MainPyOptionsWindow", "10"))
        self.comboBox_StrikePriceRange_IC.setItemText(2, _translate("MainPyOptionsWindow", "15"))
        self.comboBox_StrikePriceRange_IC.setItemText(3, _translate("MainPyOptionsWindow", "20"))
        self.comboBox_StrikePriceRange_IC.setItemText(4, _translate("MainPyOptionsWindow", "25"))
        self.comboBox_StrikePriceRange_IC.setItemText(5, _translate("MainPyOptionsWindow", "30"))
        self.comboBox_StrikePriceRange_IC.setItemText(6, _translate("MainPyOptionsWindow", "35"))
        self.comboBox_StrikePriceRange_IC.setItemText(7, _translate("MainPyOptionsWindow", "40"))
        self.comboBox_StrikePriceRange_IC.setItemText(8, _translate("MainPyOptionsWindow", "45"))
        self.comboBox_StrikePriceRange_IC.setItemText(9, _translate("MainPyOptionsWindow", "50"))
        self.comboBox_StrikePriceMultiple_IC.setItemText(0, _translate("MainPyOptionsWindow", "5"))
        self.comboBox_StrikePriceMultiple_IC.setItemText(1, _translate("MainPyOptionsWindow", "10"))
        self.comboBox_StrikePriceMultiple_IC.setItemText(2, _translate("MainPyOptionsWindow", "15"))
        self.comboBox_StrikePriceMultiple_IC.setItemText(3, _translate("MainPyOptionsWindow", "20"))
        self.radioButton_Call_IC.setText(_translate("MainPyOptionsWindow", "Call"))
        self.radioButton_Put_IC.setText(_translate("MainPyOptionsWindow", "Put"))
        self.radioButton_MktDataType_Frozen_IC.setText(_translate("MainPyOptionsWindow", "Frozen"))
        self.radioButton_MktDataType_Live_IC.setText(_translate("MainPyOptionsWindow", "Live"))
        self.label_20.setText(_translate("MainPyOptionsWindow", "Market Data Type"))
        self.label_18.setText(_translate("MainPyOptionsWindow", "TextLabel"))
        self.actionIBToolbar.setWindowTitle(_translate("MainPyOptionsWindow", "toolBar_2"))
        self.connectToIB.setText(_translate("MainPyOptionsWindow", "Connect to IB "))
        self.connectToIB.setToolTip(_translate("MainPyOptionsWindow", "Connect to IB api"))
        self.actiontestIB.setText(_translate("MainPyOptionsWindow", "test"))
        self.actiontestIB.setToolTip(_translate("MainPyOptionsWindow", "Bark"))
        self.actiontestCheckableIB.setText(_translate("MainPyOptionsWindow", "testCheckable"))
        self.actiontestCheckableIB.setToolTip(_translate("MainPyOptionsWindow", "Meow"))
        self.actionIron_Condor.setText(_translate("MainPyOptionsWindow", "Iron Condor"))
        self.actionVertical_Spreads.setText(_translate("MainPyOptionsWindow", "Vertical Spreads"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainPyOptionsWindow = QtWidgets.QMainWindow()
    ui = Ui_MainPyOptionsWindow()
    ui.setupUi(MainPyOptionsWindow)
    MainPyOptionsWindow.show()
    sys.exit(app.exec_())

